# Generated by Django 2.1 on 2018-08-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=40)),
                ('gender', models.CharField(default='dummy', max_length=10)),
                ('lease', models.PositiveIntegerField(default=600)),
                ('phone', models.CharField(default='dummy', max_length=20)),
                ('propertypic', models.CharField(default='dummy', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='dummy', max_length=50)),
                ('password', models.CharField(default='dummy', max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=3)),
                ('gender', models.CharField(default='dummy', max_length=10)),
                ('profilepic', models.CharField(default='dummy', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hackthe6ix.Person'),
        ),
    ]
