# Generated by Django 2.1 on 2018-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthe6ix', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='dummy', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='profilepic',
            field=models.CharField(default='dummy', max_length=70),
        ),
        migrations.AlterField(
            model_name='listings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
