# Generated by Django 2.1 on 2018-08-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthe6ix', '0003_auto_20180825_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='street_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='house_number',
        ),
        migrations.AddField(
            model_name='listings',
            name='gender',
            field=models.CharField(default='dummy', max_length=10),
        ),
        migrations.AddField(
            model_name='listings',
            name='phone',
            field=models.CharField(default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='listings',
            name='propertypic',
            field=models.CharField(default='dummy', max_length=70),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='dummy', max_length=10),
        ),
    ]
