# Generated by Django 2.1 on 2018-08-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackthe6ix', '0004_auto_20180825_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='lease_length',
            new_name='lease',
        ),
    ]
